### ISSUE TITLE
Does this library run on Android?

### ISSUE THREAD

**Issue by hololeo** [shrhdk/theta4j#3]
Hi 

this is a great library. thank you for making it
does this library run on android? why the decision to code it in jdk 1.7?

**Comment by shrhdk** [comment]
Hi,

Thank you for your interest :smile: 

I think you can use it on the Android 4.4+ (API 19+).
This code uses `try-with-resources`, and the API 18 does not support it.

I am working on new version `0.5.0` which supports old Android system.
Please look forward to it. It will be released on next weekend.

**Comment by shrhdk** [comment]
Oops, I tried to build for Android and I found a mistake.

[`0.4.0`](https://github.com/shrhdk/theta4j/tree/0.4.0) includes bad package for Android.

I pushed fixed commit a895a01fb3abfef6ed8b140296771622492c5642.

**Comment by hololeo** [comment]
ok thank you for your response. i need something that works with api level 15 at least.
i look forward to your new release

**Comment by shrhdk** [comment]
@hololeo 

I released version `0.5.0`.
http://search.maven.org/#artifactdetails%7Corg.theta4j%7Ctheta4j%7C0.5.0%7Cjar

It supports Android API Level 9+. Please try it out.
